import Link from 'next/link'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: {
    template: '%s | Birbal Blog',
    default: 'Birbal Blog — AI-Powered Insights',
  },
  description: 'Discover trending topics, expert insights, and in-depth articles powered by AI research.',
  openGraph: {
    type: 'website',
    siteName: 'Birbal Blog',
  },
}

export default function BlogLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="min-h-screen bg-white">
      {/* Blog Header */}
      <header className="border-b bg-white sticky top-0 z-50">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <Link href="/blog" className="flex items-center space-x-2">
            <span className="text-xl font-bold text-gray-900">Birbal</span>
            <span className="text-sm text-gray-500">Blog</span>
          </Link>
          <nav className="hidden md:flex items-center space-x-6">
            <Link href="/blog" className="text-sm text-gray-600 hover:text-gray-900 transition-colors">
              All Posts
            </Link>
            <Link href="/blog/category/Technology" className="text-sm text-gray-600 hover:text-gray-900 transition-colors">
              Technology
            </Link>
            <Link href="/blog/category/AI" className="text-sm text-gray-600 hover:text-gray-900 transition-colors">
              AI
            </Link>
            <Link href="/blog/category/Tutorials" className="text-sm text-gray-600 hover:text-gray-900 transition-colors">
              Tutorials
            </Link>
            <Link href="/rss.xml" className="text-sm text-orange-500 hover:text-orange-600 transition-colors">
              RSS
            </Link>
          </nav>
        </div>
      </header>

      {/* Blog Content */}
      <main>{children}</main>

      {/* Blog Footer */}
      <footer className="border-t bg-gray-50 mt-16">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div>
              <h3 className="font-bold text-gray-900 mb-3">Birbal Blog</h3>
              <p className="text-sm text-gray-600">
                AI-powered insights and trending analysis, auto-generated and fact-checked.
              </p>
            </div>
            <div>
              <h3 className="font-bold text-gray-900 mb-3">Links</h3>
              <ul className="space-y-2">
                <li><Link href="/blog" className="text-sm text-gray-600 hover:text-gray-900">All Posts</Link></li>
                <li><Link href="/sitemap.xml" className="text-sm text-gray-600 hover:text-gray-900">Sitemap</Link></li>
                <li><Link href="/rss.xml" className="text-sm text-gray-600 hover:text-gray-900">RSS Feed</Link></li>
              </ul>
            </div>
            <div>
              <h3 className="font-bold text-gray-900 mb-3">Powered By</h3>
              <p className="text-sm text-gray-600">
                Content generated by Gemini AI with Google Search grounding, fact-checked by AI review agents.
              </p>
            </div>
          </div>
          <div className="mt-8 pt-8 border-t text-center text-sm text-gray-500">
            &copy; {new Date().getFullYear()} Birbal. All rights reserved.
          </div>
        </div>
      </footer>
    </div>
  )
}
